### PR TITLE
Update prog_2.py

### PR DESCRIPTION
**Pull request by IRB0T**
hi there i found some issues with your code please see this one.

### CODE REVIEW

**Comment by IRB0T** [comment]
editied

**Comment by TarangRanpara** [comment]
I think, we both are doing the same thing. you are taking manual input from user for each candle & i'm taking random numbers from fixed range.

**Comment by TarangRanpara** [comment]
let me know, if i am wrong.

**Comment by IRB0T** [comment]
true, but we need to take input from user. (no issues you are doing right) but in the problem statement we need to take input from user.

**Comment by TarangRanpara** [comment]
Okay!
I'll make changes accordingly!

Thanks!
*Tjr. *

**Pull request closed without merging**
